### ISSUE TITLE
Debugging support?

### ISSUE THREAD

**Issue by merqlove** [processone/iconv#9]
Seems that iconv is not debuggable...

Can we eliminate support for this?

Tried with Erlang 1.9.3.x, Elixir 1.5.0-dev

```
[error] failed to load NIF 
_build/dev/lib/iconv/priv/lib/iconv: Library module name 'iconv' does not match calling module 'dbg_debugged'

=INFO REPORT==== 23-Jun-2017::22:49:17 ===
    application: logger
    exited: stopped
    type: temporary
*DBG* 'Elixir.IntellijElixir.DebugServer' got {'DOWN',#Ref<0.0.4.173>,
                                               process,<0.532.0>,
                                               {#{'__exception__' => true,
                                                  '__struct__' => 'Elixir.Mix.Error',
                                                  message => <<"Could not start application iconv: :iconv_app.start(:normal, []) returned an error: :bad_lib">>,
                                                  mix => true},
                                                [{'Elixir.Mix',raise,1,
                                                  [{file,"lib/mix.ex"},
                                                   {line,279}]},
                                                 {'Elixir.Enum',
                                                  '-each/2-lists^foreach/1-0-',
                                                  2,
                                                  [{file,"lib/enum.ex"},
                                                   {line,676}]},
                                                 {'Elixir.Enum',each,2,
                                                  [{file,"lib/enum.ex"},
                                                   {line,676}]},
                                                 {'Elixir.Mix.Tasks.App.Start',
                                                  start,2,
                                                  [{file,
                                                    "lib/mix/tasks/app.start.ex"},
                                                   {line,97}]},
                                                 {'Elixir.Mix.Tasks.App.Start',
                                                  run,1,
                                                  [{file,
                                                    "lib/mix/tasks/app.start.ex"},
                                                   {line,78}]},
                                                 {'Elixir.Mix.Task',run_task,
                                                  3,
                                                  [{file,"lib/mix/task.ex"},
                                                   {line,301}]},
                                                 {'Elixir.Mix.Tasks.Run',run,
                                                  5,
                                                  [{file,
                                                    "lib/mix/tasks/run.ex"},
                                                   {line,87}]},
                                                 {'Elixir.Mix.Tasks.Run',run,
                                                  1,
                                                  [{file,
                                                    "lib/mix/tasks/run.ex"},
                                                   {line,54}]},
                                                 {'Elixir.Mix.Task',run_task,
                                                  3,
                                                  [{file,"lib/mix/task.ex"},
                                                   {line,301}]}]}}

=ERROR REPORT==== 23-Jun-2017::22:49:17 ===
Error in process <0.532.0> with exit value:
{#{'__exception__' => true,
   '__struct__' => 'Elixir.Mix.Error',
   message => <<"Could not start application iconv: :iconv_app.start(:normal, []) returned an error: :bad_lib">>,
   mix => true},
 [{'Elixir.Mix',raise,1,[{file,"lib/mix.ex"},{line,279}]},
  {'Elixir.Enum','-each/2-lists^foreach/1-0-',2,
                 [{file,"lib/enum.ex"},{line,676}]},
  {'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,676}]},
  {'Elixir.Mix.Tasks.App.Start',start,2,
                                [{file,"lib/mix/tasks/app.start.ex"},
                                 {line,97}]},
  {'Elixir.Mix.Tasks.App.Start',run,1,
                                [{file,"lib/mix/tasks/app.start.ex"},
                                 {line,78}]},
  {'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,301}]},
  {'Elixir.Mix.Tasks.Run',run,5,[{file,"lib/mix/tasks/run.ex"},{line,87}]},
  {'Elixir.Mix.Tasks.Run',run,1,[{file,"lib/mix/tasks/run.ex"},{line,54}]},
  {'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,301}]}]}

=ERROR REPORT==== 23-Jun-2017::22:49:17 ===
** Generic server 'Elixir.IntellijElixir.DebugServer' terminating 
** Last message in was {'DOWN',#Ref<0.0.4.173>,process,<0.532.0>,
                           {#{'__exception__' => true,
                              '__struct__' => 'Elixir.Mix.Error',
                              message => <<"Could not start application iconv: :iconv_app.start(:normal, []) returned an error: :bad_lib">>,
                              mix => true},
                            [{'Elixir.Mix',raise,1,
                                 [{file,"lib/mix.ex"},{line,279}]},
                             {'Elixir.Enum','-each/2-lists^foreach/1-0-',2,
                                 [{file,"lib/enum.ex"},{line,676}]},
                             {'Elixir.Enum',each,2,
                                 [{file,"lib/enum.ex"},{line,676}]},
                             {'Elixir.Mix.Tasks.App.Start',start,2,
                                 [{file,"lib/mix/tasks/app.start.ex"},
                                  {line,97}]},
                             {'Elixir.Mix.Tasks.App.Start',run,1,
                                 [{file,"lib/mix/tasks/app.start.ex"},
                                  {line,78}]},
                             {'Elixir.Mix.Task',run_task,3,
                                 [{file,"lib/mix/task.ex"},{line,301}]},
                             {'Elixir.Mix.Tasks.Run',run,5,
                                 [{file,"lib/mix/tasks/run.ex"},{line,87}]},
                             {'Elixir.Mix.Tasks.Run',run,1,
                                 [{file,"lib/mix/tasks/run.ex"},{line,54}]},
                             {'Elixir.Mix.Task',run_task,3,
                                 [{file,"lib/mix/task.ex"},{line,301}]}]}}
** When Server state == #{ref => #Ref<0.0.4.173>,
                          socket => #Port<0.13957>,
                          task => {<<"phoenix.server">>,[]}}
** Reason for termination == 
** {#{'__exception__' => true,
      '__struct__' => 'Elixir.Mix.Error',
      message => <<"Could not start application iconv: :iconv_app.start(:normal, []) returned an error: :bad_lib">>,
      mix => true},
    [{'Elixir.Mix',raise,1,[{file,"lib/mix.ex"},{line,279}]},
     {'Elixir.Enum','-each/2-lists^foreach/1-0-',2,
                    [{file,"lib/enum.ex"},{line,676}]},
     {'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,676}]},
     {'Elixir.Mix.Tasks.App.Start',start,2,
                                   [{file,"lib/mix/tasks/app.start.ex"},
                                    {line,97}]},
     {'Elixir.Mix.Tasks.App.Start',run,1,
                                   [{file,"lib/mix/tasks/app.start.ex"},
                                    {line,78}]},
     {'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,301}]},
     {'Elixir.Mix.Tasks.Run',run,5,[{file,"lib/mix/tasks/run.ex"},{line,87}]},
     {'Elixir.Mix.Tasks.Run',run,1,[{file,"lib/mix/tasks/run.ex"},{line,54}]},
     {'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,301}]}]}
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (Mix.Error) Could not start application iconv: :iconv_app.start(:normal, []) returned an error: :bad_lib
        (mix) lib/mix.ex:279: Mix.raise/1
        (elixir) lib/enum.ex:676: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir) lib/enum.ex:676: Enum.each/2
        (mix) lib/mix/tasks/app.start.ex:97: Mix.Tasks.App.Start.start/2
        (mix) lib/mix/tasks/app.start.ex:78: Mix.Tasks.App.Start.run/1
        (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
        (mix) lib/mix/tasks/run.ex:87: Mix.Tasks.Run.run/5
        (mix) lib/mix/tasks/run.ex:54: Mix.Tasks.Run.run/1
        (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
```

**Comment by prefiks** [comment]
Error 'bad_lib' that you are getting here is most likely a result of having iconv compiled with different version or erlang than you trying to run it with. I don't see reason to not be able to make it work when you compile it correctly

**Comment by merqlove** [comment]
It run’s well in dev/prod mode. Error only in debug.

--
Best regards,
Alexander Merkulov

E-mail: sasha@merqlove.ru
Tel.:  +7(925) 278-44-98
Skype:  merqlove

**Comment by prefiks** [comment]
Yeah, probably your debugger is using different version of erlang than when you running it not in debug mode.

**Comment by merqlove** [comment]
@KronicDeth, can it be such thing?

**Comment by KronicDeth** [comment]
@merqlove the debugger is launched with [a mix task](https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/resources/debugger/lib/debug_task.ex) that runs [`loadconfig` and `compile`](https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/resources/debugger/lib/debug_task.ex#L12-L13), so as long as `compile` can pick up the SDK difference between a compile you did outside IntelliJ and the SDK version you have selected for the project when you launch the test you should get a recompile for the SDK, but rebuilding on changing your SDK version is actually not a supported rebuild reason for Elixir in my experience (they usually ask me to delete `_build` when this happens), so

1. Check that the version of Elixir (and Erlang) you used to compile in the terminal matches the SDK version you selected in IntelliJ
2. Delete/Move the `_build` directory, so that a full recompile is forced when you launch the debugger.

If you do (2) and there's still an Erlang version mismatch, we'll go from there.

**Comment by merqlove** [comment]
@KronicDeth 
1. Yeah, same version.

No debug:
```
Generated some_app app
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

1.5.0-dev
```

Debug:
```
*DBG* 'Elixir.IntellijElixir.DebugServer' got {tcp,#Port<0.66962>,
                                               <<131,104,1,100,0,8,114,117,
                                                 110,95,116,97,115,107>>}
*DBG* 'Elixir.IntellijElixir.DebugServer' new state #{ref=>#Ref<0.1135425933.3607101444.222185>,socket=>#Port<0.66962>,task=>{<<115,111,109,101,95,97,112,112,46,101,114,108,97,110,103,95,118,101,114,115,105,111,110>>,[]}}
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

1.5.0-dev
*DBG* 'Elixir.IntellijElixir.DebugServer' got {'DOWN',
                                               #Ref<0.1135425933.3607101444.222185>,
                                               process,<0.2261.0>,normal}
```

2. Yep, tried to delete _build/deps folders. Not works.
